// <auto-generated />
using System;
using DigitalControlTower.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DigitalControlTower.Web.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DigitalControlTower.Web.Models.ActionHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ActionItemId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("At")
                        .HasColumnType("datetime2");

                    b.Property<string>("By")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FromValue")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("ToValue")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.HasIndex("ActionItemId", "At");

                    b.ToTable("ActionHistories");
                });

            modelBuilder.Entity("DigitalControlTower.Web.Models.ActionItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CheckResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("CompletionDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("NextStep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Quarter")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Recurrence")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateOnly?>("ReviewDate")
                        .HasColumnType("date");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("SuccessCriteria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Target")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WorkItemId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Owner");

                    b.HasIndex("Serial")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("WorkItemId");

                    b.ToTable("Actions");
                });

            modelBuilder.Entity("DigitalControlTower.Web.Models.ActionTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionItemId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("ActionItemId", "Tag")
                        .IsUnique();

                    b.ToTable("ActionTags");
                });

            modelBuilder.Entity("DigitalControlTower.Web.Models.ActionWeek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionItemId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Mark")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("WeekIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActionItemId", "WeekIndex")
                        .IsUnique();

                    b.ToTable("ActionWeeks");
                });

            modelBuilder.Entity("DigitalControlTower.Web.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DigitalControlTower.Web.Models.Comment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ActionItemId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkItemId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("ActionItemId");

                    b.HasIndex("WorkItemId");

                    b.ToTable("Comments", t =>
                        {
                            t.HasCheckConstraint("CK_Comments_SingleParent", "([ActionItemId] IS NOT NULL AND [WorkItemId] IS NULL) OR ([ActionItemId] IS NULL AND [WorkItemId] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("DigitalControlTower.Web.Models.Pillar", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Pillars");
                });

            modelBuilder.Entity("DigitalControlTower.Web.Models.Project", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateOnly?>("ActualCompletionDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("BaselineDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("CostAvoidance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeptOwner")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DigitalOwnerId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ImplementationDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("LabourHoursSaving")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PillarId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Pm")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal?>("ProductivityImprovement")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SavingsType")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Scope")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DigitalOwnerId");

                    b.HasIndex("PillarId");

                    b.HasIndex("Status");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("DigitalControlTower.Web.Models.SerialCounter", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("LastValue")
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.ToTable("SerialCounters");
                });

            modelBuilder.Entity("DigitalControlTower.Web.Models.WeekDate", b =>
                {
                    b.Property<int>("WeekIndex")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("WeekIndex");

                    b.ToTable("WeekDates");
                });

            modelBuilder.Entity("DigitalControlTower.Web.Models.WorkItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("WorkItems");
                });

            modelBuilder.Entity("DigitalControlTower.Web.Models.ActionHistory", b =>
                {
                    b.HasOne("DigitalControlTower.Web.Models.ActionItem", "ActionItem")
                        .WithMany("History")
                        .HasForeignKey("ActionItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionItem");
                });

            modelBuilder.Entity("DigitalControlTower.Web.Models.ActionItem", b =>
                {
                    b.HasOne("DigitalControlTower.Web.Models.WorkItem", "WorkItem")
                        .WithMany("Actions")
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkItem");
                });

            modelBuilder.Entity("DigitalControlTower.Web.Models.ActionTag", b =>
                {
                    b.HasOne("DigitalControlTower.Web.Models.ActionItem", "ActionItem")
                        .WithMany("Tags")
                        .HasForeignKey("ActionItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionItem");
                });

            modelBuilder.Entity("DigitalControlTower.Web.Models.ActionWeek", b =>
                {
                    b.HasOne("DigitalControlTower.Web.Models.ActionItem", "ActionItem")
                        .WithMany("Weeks")
                        .HasForeignKey("ActionItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionItem");
                });

            modelBuilder.Entity("DigitalControlTower.Web.Models.Comment", b =>
                {
                    b.HasOne("DigitalControlTower.Web.Models.ActionItem", "ActionItem")
                        .WithMany("Comments")
                        .HasForeignKey("ActionItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DigitalControlTower.Web.Models.WorkItem", "WorkItem")
                        .WithMany("Comments")
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActionItem");

                    b.Navigation("WorkItem");
                });

            modelBuilder.Entity("DigitalControlTower.Web.Models.Project", b =>
                {
                    b.HasOne("DigitalControlTower.Web.Models.AppUser", "DigitalOwner")
                        .WithMany("OwnedProjects")
                        .HasForeignKey("DigitalOwnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DigitalControlTower.Web.Models.Pillar", "Pillar")
                        .WithMany("Projects")
                        .HasForeignKey("PillarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DigitalOwner");

                    b.Navigation("Pillar");
                });

            modelBuilder.Entity("DigitalControlTower.Web.Models.WorkItem", b =>
                {
                    b.HasOne("DigitalControlTower.Web.Models.Project", "Project")
                        .WithMany("Items")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DigitalControlTower.Web.Models.ActionItem", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("History");

                    b.Navigation("Tags");

                    b.Navigation("Weeks");
                });

            modelBuilder.Entity("DigitalControlTower.Web.Models.AppUser", b =>
                {
                    b.Navigation("OwnedProjects");
                });

            modelBuilder.Entity("DigitalControlTower.Web.Models.Pillar", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("DigitalControlTower.Web.Models.Project", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("DigitalControlTower.Web.Models.WorkItem", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
